apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.16.2
    helm:
      valuesObject:
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: auto
        ingress:
          hosts:
            core: repository.wush.site
        annotations:
          ingress.kubernetes.io/ssl-redirect: "true"
          ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          cert-manager.io/acme-challenge-type: "http01"
          acme.cert-manager.io/http01-edit-in-place: "true"
          external-dns.alpha.kubernetes.io/hostname: repository.wush.site
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true