apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    chart: harbor
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 24.3.0
    helm:
      valuesObject:
        adminPassword: "Harbor12345"
        externalURL: https://harbor.wush.site
        exposureType: ingress
        ingress:
          core:
            ingressClassName: "nginx"
            hostname: harbor.wush.site
            annotations:
              external-dns.alpha.kubernetes.io/hostname: harbor.wush.site
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            extraTls:
              - hosts:
                  - harbor.wush.site
                secretName: wildcard-wush-site-tls
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - harbor
                topologyKey: "kubernetes.io/hostname"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
