apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    chart: harbor
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 24.2.0
    helm:
      valuesObject:
        externalURL: https://container.wush.site
        exposureType: ingress
        ingress:
          core:
            ingressClassName: "nginx"
            controller: default
            hostname: container.wush.site
            annotations:
              ingress.kubernetes.io/proxy-body-size: "0"
              ingress.kubernetes.io/client-max-body-size: "0"
              ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/client-max-body-size: "0"
              cert-manager.io/cluster-issuer: letsencrypt-prod
              external-dns.alpha.kubernetes.io/hostname: container.wush.site
            tls: true
        registry:
          relativeurls: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true