global:
  domain: argocd.wush.site

configs:
  params:
    server.insecure: true
  cm:
    admin.enabled: true
    application.instanceLabelKey: argocd.argoproj.io/instance
  secret:
    argocdServerAdminPassword: "$2y$10$DeFHUuHjInpGt2UcuJqwaOTfR1yYybLyNFtkRUPmaTahQzYmiiPGm"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      cert-manager.io/acme-challenge-type: "http01"
      acme.cert-manager.io/http01-edit-in-place: "true"
    tls:
      - hosts:
          - argocd.wush.site
        secretName: argocd-tls

repoServer:
  autoscale:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

controller:
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi