controller:
  enabled: true
  electionID: "nginx-ingress-leader-election"
  service:
    type: LoadBalancer
  config:
    entries:
      proxy-body-size: "0"
      client-max-body-size: "0"
enableCertManager: true
enableExternalDNS: true
ingressClass:
  setAsDefaultIngress: true
