# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: mongodb
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: mongodb
#     repoURL: https://charts.bitnami.com/bitnami
#     targetRevision: 16.2.1
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: backend
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true