#beforeinstall
#kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v4.0.0/deploy/crds.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://helm.nginx.com/stable
    targetRevision: 2.0.0
    helm:
      valuesObject:
        controller:
          enabled: true
          service:
            type: LoadBalancer
        enableCertManager: true
        enableExternalDNS: true
        ingressClass:
          setAsDefaultIngress: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true