apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://helm.nginx.com/stable
    targetRevision: 2.0.0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true