apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami/external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.7.1
    helm:
      valuesObject:
        provider: cloudflare
        cloudflare: 
          apiToken: "Wgd4SflGUTe8njPc9SA507OcxJlnOUruzdSNpbIC"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true