apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.7.0
    helm:
      valuesObject:
        provider: cloudflare
        cloudflare: 
          apiToken: "jE-ZtHnaL0tJElF-4aMgDSems7x48G6Izlw8hVLA"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: internal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true