apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-b
  namespace: argocd
spec:
  description: "Project for microservices"
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
