apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
spec:
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: ''
    namespace: tools
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.4.0
    chart: mongodb
    helm:
      releaseName: mongodb
      valuesObject:
        useStatefulSet: true
