apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: ''
    namespace: tools
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.2.4
    chart: nginx
    helm:
      releaseName: nginx
      valuesObject:
        image: 1.27.3-debian-12-r0