project: default
source:
  repoURL: https://charts.bitnami.com/bitnami
  targetRevision: 18.2.4
  chart: nginx
  helm:
    releaseName: nginx
    valuesObject:
      image: 1.27.3-debian-12-r0
destination:
  server: https://kubernetes.default.svc
  namespace: backend
syncPolicy:
  automated:
    prune: true
    selfHeal: true